import Head from 'next/head'
import { useState } from 'react'

// Import internals
import Header from '../components/common/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import Skills from '../components/Skills'
import Portfolio from '../components/Portfolio'
import Footer from '../components/Footer'

export default function Home() {
  const [hideHeader, setHideHeader] = useState(false)

  return (
    <div>
      <Head>
        <title>Mikyle Reyes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/notion-avatar-1663964359003.svg' />
      </Head>

      <div className='relative'>
        {hideHeader ? <Header hidden={'hidden'} /> : <Header />}
        <Hero />
        <About setHideHeader={setHideHeader} />
        <Skills />
        <Portfolio />
        <Footer />
      </div>
    </div>
  )
}
