import Head from 'next/head'

// Import internals
import Header from '../components/common/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import Skills from '../components/Skills'
import PortfolioHome from '../components/Portfolio-Home'
import Footer from '../components/common/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mikyle Reyes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/notion-avatar-1663964359003.svg' />
      </Head>

      <div className='relative'>
        <Header />
        <Hero />
        {/* <About /> */}
        <PortfolioHome />
        <Skills />
        <Footer />
      </div>
    </div>
  )
}
